### ISSUE TITLE
Error on initialising

### ISSUE THREAD

**Issue by augustocdias** [williamboman/nvim-lsp-installer#105]
I'm having the following error when I call `is_installed`

```
E5113: Error while calling lua chunk: ...art/nvim-lsp-installer/lua/nvim-lsp-installer/server.lua:70: attempt to index local 'self' (a nil value)
```

Here's my config:

```lua
function ensure_server(name)
    local lsp_installer = require'nvim-lsp-installer.servers'
    local _, server = lsp_installer.get_server(name)
    if not server.is_installed() then
        server.install()
    end
    return server
end

ensure_server('pyright')
ensure_server('tsserver')
local rust_server = ensure_server('rust_analyzer')
require('rust-tools').setup({
    tools = {
        autoSetHints = true,
        hover_with_actions = true,
        inlay_hints = {
            show_parameter_hints = true,
            parameter_hints_prefix = '',
            other_hints_prefix = '',
        },
    },
    server = {
        on_attach = lsp_status.on_attach,
        capabilities = lsp_status.capabilities,
        cmd = rust_server.get_default_options().cmd,
        settings = {
            ['rust-analyzer'] = {
                 ...
            }
        }
    }
})
```

Am I doing something wrong?

**Comment by augustocdias** [comment]
My mistake. I should be using `:` instead of `.`

**Comment by augustocdias** [comment]
This error is appearing in my messages though:

```
Error executing vim.schedule lua callback: Vim:E158: Invalid buffer name: 1
Client 1 quit with exit code 1 and signal 0
```

**Comment by williamboman** [comment]
Yeah `:` instead of `.` would be the first issue :+1:. One thing I noticed is that you're calling the `rust-tools.setup()` method immediately - this might be problematic in cases where nvim-lsp-installer hasn't finished installing rust_analyzer. `server:install()` will only queue the server to be installed asynchronously. You might want to make use of the `on_server_ready(fn)` function to make sure to only set up servers once they're successfully been installed, like so:

```lua
lsp_installer.on_server_ready(function(server)
  local opts = {} -- same as the object passed to lspconfig's setup method
  if server.name == "rust_analyzer" then
    require("rust-tools").setup({...})
  else
    server:setup(opts)
  end
end)
```

> This error is appearing in my messages though:
> 
> ```
> Error executing vim.schedule lua callback: Vim:E158: Invalid buffer name: 1
> Client 1 quit with exit code 1 and signal 0
> ```

Do you happen to be on Windows? `:doautoall` (which `vim.cmd [[ do User LspAttachBuffers ]]` triggers) seems to have a tendency to dispatch autocmds on buffers that are no longer valid on Windows. This should not cause any issues though and you can ignore that particular error message. I'll see if it'd be possible to run it silently to get rid of that error message.

As for why the client is exiting, it could be due to my very first answer - the server hasn't finished installing? What does the LSP logs say (`:lua vim.cmd('e'..vim.lsp.get_log_path())`)?

**Comment by augustocdias** [comment]
the logs contain only some warnings from the lsps themselves. I'll use your suggestion to call the `on_server_ready`.
