### ISSUE TITLE
Windows LspInstall clangd not working

### ISSUE THREAD

**Issue by dantearaujo1** [williamboman/nvim-lsp-installer#112]
When i try to install clangd server with LspInstall clangd it doesn't finish installing never and after restart neovim it lsp says that the exe is not executable.

After LspInstall clangd command:
  Pending servers (1)
    ◍ clangd (running) PS D:\Code\Configurations\nvim\nvim-data\lsp_servers\clangd> 

Never change ^

 Config: clangd
 	filetypes:         c, cpp, objc, objcpp
 	root directory:    D:\Code
 	cmd:               D:\Code\Configurations\nvim\nvim-data\lsp_servers\clangd\clangd
 	cmd is executable: Unable to find executable. Please check your path and ensure the server is installed
 	autostart:         true
 	custom handlers:

**Comment by dantearaujo1** [comment]
It worked after changing this default_options to this executable path: 
       default_options = {
            cmd = { path.concat { root_dir, "clangd_12.0.1/bin/clangd" } },
        },

**Comment by williamboman** [comment]
Hey! This seems to be an issue when creating the symlink, the callback is never called so the installer hangs. When you restart neovim (or launch a new instance) it'll think clangd was successfully installed because the directory exists - but the `cmd` will be pointing to a symlink that was never created.

I think I found a fix for it, could you try the `windows-clangd` branch?

**Comment by dantearaujo1** [comment]
it worked! Thank you!
