### ISSUE TITLE
Possible for installation to fail due to the process closing, but later `installer` will think it is installed

### ISSUE THREAD

**Issue by IndianBoy42** [williamboman/nvim-lsp-installer#154]
So I setup autoinstall of some lsp servers, and I guess I closed nvim while an install was going on the background. This meant the download was partially done and not extracted. Yet when I reopened nvim, I started getting errors that the LSP was not executable even though `LspInstallInfo` showed no errors.

I think the `already installed` checked could be made more intelligent, like not just looking for the folder but the executable inside, or have a separate db/log of which LSPs are installed which is only updated *after* the installation scripts finishes completely

**Comment by williamboman** [comment]
Hey! Yeah this is one my todo list. The problem stems from the fact that certain server installers are composed of more than one distinct installer step (an installer is basically just a function that receives a callback which it calls when it completes). The orchestration of an installation takes place in the main event loop of neovim. This is all fine as long as the main loop doesn't exit. If it does, the installation is effectively interrupted. This is compounded by the fact that the logic behind what's considered "installed" or not is simply whether the server install directory exists or not.

The ideas that I have are, in order of low to high complexity:
1. Run the installation for a server in a tmpdir. Upon successful installation, move the tmpdir to the server's intended install dir.
2. Implement cancellation capabilities in all installers, and make sure to run these when neovim exits. (this will likely introduce other edge cases though)
3. Lift the orchestration layer from neovim's main loop and spawn it as a single, detached, job.

I've not really picked this up yet, mainly because I feel like the solution to it is so simple (and if you ask me pretty intuitive) - just reinstall the server. What's blocking me atm is basically figuring out cross-platform support for tmpdirs - more precisely how Windows does it. Any input on that would be helpful :D! I'll eventually get to it though
