### ISSUE TITLE
Eslintls not using my projects .eslintrc

### ISSUE THREAD

**Issue by NICHTJ3** [williamboman/nvim-lsp-installer#19]
eslintls does not appear to be using my .eslintrc as I'm getting different errors when using efm or vscode

**Comment by NICHTJ3** [comment]
I'm actually unsure about this... The issue seams to also appear in efm now. I'm going to close this for now

**Comment by williamboman** [comment]
It should behave exactly the same as VSCode. The only potential sources of problem that I can think of would be

- nvim's LSP client behaves differently than VSCode in certain areas
- After reviewing and debugging the eslint language server source, I ended up providing [these](https://github.com/williamboman/nvim-lsp-installer/blob/main/lua/nvim-lsp-installer/servers/eslintls/init.lua#L34-L43) settings to the LSP server, in order to get it to work. However, unless these internals have changed in eslint LSP I'd be surprised if this is causing issues.

**Comment by NICHTJ3** [comment]
Yeah turns out the error was showing in all of them it was just taking a while to show in vscode 🤷
