### ISSUE TITLE
go installer: use the install subcommand

### ISSUE THREAD

**Issue by williamboman** [williamboman/nvim-lsp-installer#229]
[`go get <pkg>` has been deprecated for installing executables.](https://golang.org/doc/go-get-install-deprecation) The recommended subommand to use is `go install`, since Go 1.17.

More discussions and potential implementations can be found in #138.

**Comment by dhollinger** [comment]
From what I can tell here: https://cs.opensource.google/go/go/+/refs/tags/go1.11:src/cmd/go/internal/work/build.go

`go install` has been around quite a while. Since Go 1.11 at least (unless I'm misreading the code). This probably needs to be addressed sooner than later as the Go Documentation, it notes that `go get` will no longer build packages starting in Go 1.18 and `go install` will need to be used before/by then: https://golang.org/doc/go-get-install-deprecation

**Comment by reynn** [comment]
@williamboman I think you want to do this instead

```shell
$ GOBIN=$PWD go install golang.org/x/tools/gopls@latest
```

no initializing a module first the @latest part is required for the install command... it seems?

**Comment by williamboman** [comment]
Fixed in #438!
