### ISSUE TITLE
Option to provide GitHub API token?

### ISSUE THREAD

**Issue by rosenhouse** [williamboman/nvim-lsp-installer#248]
Hi, I'm trying this out, but my machine is behind a shared IP and we often hit API rate limiting from GitHub.

e.g. on my machine
```
$ curl https://api.github.com/repos/clangd/clangd/releases/latest
{"message":"API rate limit exceeded for <MY_IP_ADDRESS>. (But here's the good news: Authenticated requests get a higher rate limit. Check out t
he documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

so when I go to `:LspInstall something` I see 
```
   ▏   ▏   ▏   ▏   ▏   ▏   ▏   ▏   ▏   ▏     nvim-lsp-installer
   ▏   ▏   ▏   ▏   ▏   ▏   ▏   ▏   ▏   ▏      press ? for help
   ▏   ▏   ▏   ▏   ▏   ▏     https://github.com/williamboman/nvim-lsp-installer

 Installed servers (1)
   ◍ rust_analyzer

 Pending servers (1)
   ◍ clangd (failed)
   ▏   Fetching latest release version from GitHub API...
   ▏   Failed to fetch url "https://api.github.com/repos/clangd/clangd/releases/latest".
   ▏   curl: (22) The requested URL returned error: 403
```

Is there a way I can provide a token as an environment variable or other option, so that lsp-installer can use it when doing requests to GitHub?  I've seen projects support environment variables like `GITHUB_TOKEN` or `GITHUB_API_TOKEN`.

Thank you!

**Comment by kylo252** [comment]
How about using [gh](https://github.com/cli/cli) by default when it's available? It'll handle the authentication for you without having to pass around any API keys to the environment, and it can even perform `jq` queries if needed.

We can also make it opt-in
```lua
settings = {
	---
	use_gh_cli = false,
}
```

**Comment by kylo252** [comment]
> I really want to be conservative with dependencies. Personally, had I seen a plugin like this requiring `gh` I'd nope out immediately.

@williamboman, just a reminder that it can be completely optional. I was thinking that it should help solve any rate-limiting issues with github, and not to actually completely replace anything. So basically check if it's there and then use `fetcher()` otherwise. 

It would also mean that you just tell people to use it if they're having trouble with the default `curl` or whatever the default `fetcher()` happens to be. That would be easier and more maintainable than trying to create a cross-platform OAuth solution.

**Comment by williamboman** [comment]
Semi-hacky solution in #403, wdyt?
