### ISSUE TITLE
Adding newly installed server to PATH automatically

### ISSUE THREAD

**Issue by VanillaBase1lb** [williamboman/nvim-lsp-installer#305]
I have been trying to understand how to use this for the past 2 days. How does this plugin work? Do I have to add the language server to my `PATH` every time I install a new server or should it handle everything itself and I am doing something wrong?
After installing `clangd` with `:LspInstall clangd` and opening a c++ file, I am getting this error:

<code>
Spawning language server with cmd: `clangd` failed. The language server is either not installed, missing from PATH, or not executable.</code>

However this does not occur after manually adding clangd to PATH. Also, `:LspInstallLog` show no errors.

I am leaving this issue unlabeled because I don't even know if this is expected behavior. I am using the default config.

**Comment by williamboman** [comment]
Hello! Have you seen the minimal setup example in the readme https://github.com/williamboman/nvim-lsp-installer#setup? That's the recommended way of setting up servers. It looks like you are setting servers up directly via lspconfig, through `lspconfig.clangd.setup {}`? If you do this you need to manually provide the full path to the `clangd` executable installed by this plugin, because it does not install anything to paths that are commonly found in PATH.

By calling `server:setup()` like in the example, lsp installer will automatically inject the `cmd` property for you

**Comment by VanillaBase1lb** [comment]
Yes, thank you. I got it working now. I did not realize that this setup function was supposed to be called only once in place of the lspconfig's `setup` function. My init.lua had both setup functions, which I think was causing the trouble.
