### ISSUE TITLE
Add more info about pylsp installer

### ISSUE THREAD

**Issue by Fymyte** [williamboman/nvim-lsp-installer#317]
**Realy hard to find how to add packages for plugins using `pip3` installer**
After digging for 2 days in lsp logs and codes for pylsp I finally understood how to add pylsp_mypy and pyls_isort plugins.
lsp installed with `pip3` installer seems to create a venv in the lsp_installer directory, thus not finding packages in the user system.
To install those plugins I had to source the created venv and use pip in it.

**Possible solutions**
In the first time, I think it would be great to add better installation instructions for lsp that uses pip3 installer and explicitly says that they use a virtual env, and how to add packages for them.
An even better solution would be to add the opportunity for the user to customize an existing server, to add additional packages to install in the venv. I don't know how this would be implemented tho, It's just an idea.

**Describe alternatives you've considered**
For now I had to create an entirely new server and register it in my config, just to add those missing packages automatically.
```lua
local function ensure_lsp_installed(servers)
  for _, name in pairs(servers) do
    local server_is_found, server = lsp_installer.get_server(name)
    if server_is_found then
      if not server:is_installed() then
        utils.log('warn', 'Server ' .. name .. ' not installed. Installing...')
        server:install()
      end
    end
  end
end

local custom_pylsp_name = 'pylsp-full'
local lspconfig_configs = require('lspconfig.configs')
local lspconfig_util = require('lspconfig.util')
local pip3 = require('nvim-lsp-installer.installers.pip3')
local lsp_installer_servers = require('nvim-lsp-installer.servers')
local lsp_installer_server = require('nvim-lsp-installer.server')
local root_dir = lsp_installer_server.get_server_root_path(custom_pylsp_name)
lspconfig_configs[custom_pylsp_name] = {
  default_config = {
    cmd = { 'pylsp' },
    filetypes = { 'python' },
    root_dir = function(fname)
      local root_files = {
        'pyproject.toml',
        'setup.py',
        'setup.cfg',
        'requirements.txt',
        'Pipfile',
      }
      return lspconfig_util.root_pattern(unpack(root_files))(fname) or lspconfig_util.find_git_ancestor(fname)
    end,
    single_file_support = true,
  },
}
local custom_pylsp_server = lsp_installer_server.Server:new( {
  name = custom_pylsp_name,
  root_dir = root_dir,
  installer = pip3.packages( { 'python-lsp-server[all]', 'pylsp-mypy', 'pylsp-rope', 'pyls-isort', 'pyls-flake8' } ),
  default_options = { pip3.executable(root_dir, "pylsp") },
} )
lsp_installer_servers.register(custom_pylsp_server)
local servers = { 'rust_analyzer', 'clangd', custom_pylsp_name, 'sumneko_lua', 'vimls', 'bashls', 'cmake' }
--local servers = { 'pylsp' }
ensure_lsp_installed(servers)
```
The code could probably be cleaner but it's more a proof of concept

If anything is unclear please tell me it's my first issue on an open-source project.

**Comment by williamboman** [comment]
Hello! Ah I was not aware there existed auxiliary plugins for pylsp - I thought by installing `python-lsp-server[all]` it'd install everything.

We have some other cases where a command provided by a server installation needs to be executed, for example [installing project-local TFLint plugins](https://github.com/williamboman/nvim-lsp-installer/blob/main/lua/nvim-lsp-installer/servers/tflint/init.lua#L36-L59). I think we can take the same approach here? Instead of having users manually going to the installation directory, activating the venv, and installing their packages, I think we can provide a more accessible API for it, like a custom command:

```
:PylspInstall pylsp-mypy pylsp-rope pyls-isort pyls-flake8
```

Wdyt?

**Comment by Fymyte** [comment]
Yes I think it would make things way easier.
I'm not very confident with nvim for now but I could try to replicate the work done for TFLint.
Should I close the PR and create a new one or rewrite the current I have done ?

**Comment by williamboman** [comment]
I think we can keep the same branch and PR. I use "squash merge commits" in this repository, meaning that when we merge a PR it will be squashed into a single commit with a message that defaults to the PR title - so the commit history in a feature branch doesn't matter too much at the end of the day :).

I believe we should be able to copy most of the stuff done in TFLint, with some small modifications:

```lua
{
  PylspInstall = function (...)
    proess.spawn(pip3.executable(root_dir, "pip"), {
      args = { "install", "-U", ... },
      stdio_sink = process.simple_sink(),
    }, function (success) ... end)
  end
}
```

The `...` is the "vararg" syntax for Lua, I believe it can be used like in the example above. Otherwise `vim.list_extend({ "install", "-U" }, ...)` might be needed

**Comment by williamboman** [comment]
I realized this approach might be a bit annoying when upgrading `pylsp` though, as upgrading will wipe the existing installation and replace it with the new (you'd have to then run `:PylspInstall` again). I think it's a fine trade-off for now :+1:, but we might want to consider making this more persistent somehow (maybe through a new setting item).

**Comment by Fymyte** [comment]
It seems to be a little bit harder than expected as whenever I want to add arguments to the command I get
`E488 Trailing characters`
It might be an `lspconfig` issue as I went through all supported lsp and didn't found any command which seems to have arguments.
for now I just came to
```lua
PylspInstall = {
    function (...)
        local plugins = table.pack(...)
        process.spawn(
            pip3.executable(root_dir, "pip"),
            {
                args = vim.list_extend({ "install", "-U", "--disable-pip-version-check" }, plugins),
                stdio_sink = process.simple_sink(),
            },
            vim.schedule_wrap(function(success)
                if success then
                    notify(string.format("Successfully installed %q plugins.", table.concat(plugins, ",")))
                else
                    notify "Failed to install requested plugins."
                end
            end)
        )
    end,
    description = "Install listed modules in the env of Pylsp.",
},
```
which doesn't add much from your given exemple

**Comment by williamboman** [comment]
Hmm this could be due to how lspconfig sets up these commands. Previously I did a quick look through lspconfig source and saw [this line](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/util.lua#L68) with `(<f-args>)` so I assumed they'd allow it.

Looking at the code it seems like we have to enable those flags `command!` flags ourselves. I believe either of the following ought to do it:

```lua
PylspInstall = {
  function () ... end,
  "-nargs=+"
}
-- or
PylspInstall = {
  function () ... end,
  ["nargs=+"] = true
}
```

**Comment by Fymyte** [comment]
I have added the command in the PR, and fixed the associated documentation.
There is still the question of the management of stdout and stderr to check but the command works.
I also fixed the coding style issue and used stylua locally.
