### ISSUE TITLE
New server request: nimlsp

### ISSUE THREAD

**Issue by Yabanahano** [williamboman/nvim-lsp-installer#326]
**Which server would you like to request to be added?**
Server name: `nimlsp`
Server homepage (e.g., GitHub page): https://github.com/PMunch/nimlsp

**Which languages does this server target?**
Languages: `nim`

**Comment by williamboman** [comment]
Cool! At first glance it looks like compiling the project would be the best path, as `nimble` seems to be the only other option. I'm not familiar with nimble myself, but it seems like it only really installs to a "global" location, which is not particularly compatible with this plugin. I also found https://github.com/pragmagic/vscode-nim, do you know if they're the same? I assume they are since the lspconfig entry [links to both](https://github.com/pragmagic/vscode-nim)

**Comment by zetashift** [comment]
> I also found https://github.com/pragmagic/vscode-nim, do you know if they're the same? 

They kind of aren't! Both nimlsp and the vscode extensions rely on `nimsuggest`, a tool that comes with Nim so provide better tooling support.

I agree that the best path will be compiling the project. 
One thing to note is this from nimlsp's README:

```
When compiling and using nimlsp it needs to have Nim's sources available in order to work. 
With Nim installed through choosenim these should already be on your system 
and nimlsp should be able to find and use them automatically
```

Most Nim users will have choosenim installed, but not all!

**Comment by williamboman** [comment]
Added in #406
