### ISSUE TITLE
Expose the default configuration from nvim-lspconfig to the on_server_ready callback

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [williamboman/nvim-lsp-installer#376]
**Is your feature request related to a problem? Please describe.**
At the moment, to *extend* a value from `nvim-lspconfig` (such as adding to the default `filetypes`), one either has to:

1. Copy-paste the default value,

   ```lua
   lsp_installer.on_server_ready(function(server)
      local config = make_config()

      if server.name == "jsonls" then
         -- Add jsonc
         server.filetypes = { "json", "jsonc" }
      end

      server:setup(config)
   end)
   ```

2. … or string-concat the server name into a `require()` call. Not pretty!

   ```lua
   lsp_installer.on_server_ready(function(server)
      local config = make_config()
      local filetypes = require('lspconfig.server_configurations.' .. server.name)
         .default_config.filetypes

      if server.name == "jsonls" then
         -- Add jsonc
         vim.list_extend(filetypes, { "jsonc" })
      end

      server:setup(config)
   end)
   ```

**Describe the solution you'd like**
Ideally, `default_config` would exist on the `server` argument:

```lua
lsp_installer.on_server_ready(function(server)
   local config = make_config()

   if server.name == "jsonls" then
      -- Add jsonc
      config.filetypes = vim.list_extend(server.filetypes, { "jsonc" })
   end

   server:setup(config)
end)
```

**Comment by williamboman** [comment]
Hello! Looking at this particular example, I feel like this is something that should be added to lspconfig? If jsonls supports jsonc files, I think it should be added as a default filetype!

The `server` argument is an instance of `:h nvim-lsp-installer.Server`. I can see how providing the default config from lspconfig via this class could be useful, but in the future I'd like to remove this class from the public API altogether, so I'm avoiding adding new (public) APIs to it. 

In order to access lspconfig's default config, you will have to import it directly from lspconfig as you do in your 2nd example. The way you structure the control flow inside the `.on_server_ready()` handler is up to you. If you'd like to avoid string concatenating the argument to `require`, you could lift everything up from the handler function, for example by using table structures like so:

```lua
local jsonls_config = require("lspconfig.server_configurations.jsonls").default_config
local server_opts = {
    ["jsonls"] = {
        on_attach = common_on_attach,
        filetypes = vim.list_extend({ "jsonc" }, jsonls_config.filetypes),
    },
    ["sumneko_lua"] = require("lua-dev").setup {}
}

lsp_installer.on_server_ready(function(server)
    local opts = server_opts[server.name] or {}
    server:setup(opts)
end)
```
