### ISSUE TITLE
Autofix for supported servers

### ISSUE THREAD

**Issue by sassanh** [williamboman/nvim-lsp-installer#41]
Thanks for this neat plugin!

Now that we have eslintls and it is using vscode-eslint, can we have the feature provided by `source.fixAll.eslint`in vscode-eslint so that listing issues are resolved on save? Personally I don't like coc.nvim approach of providing a json config file similar to vscode's config file. I would prefer a flag in lua setup function of this plugin so that we are sticking with neovim environment patterns for configuration rather than bringing vscode style configuration to neovim.

**Comment by williamboman** [comment]
Hey! Seems like the upstream ESLint server doesn't report support for the `textDocument/formatting` capability, when in fact it does support it ("formatting" and "auto fixing" is the same thing in eslint's implementation). [I opened a PR](https://github.com/microsoft/vscode-eslint/pull/1307) to fix this.

With ESLint starting to report this capability, you should be able to format the current buffer via built-in LSP methods:

```lua
vim.lsp.buf.formatting()
```

You could then for example hook this lua function call to any AutoCmd, like `autocmd BufPostWrite :lua vim.lsp.buf.formatting()`. _Note that if there are more than 1 client currently attached which support this capability, neovim will prompt which one you want to source formatting changes from._ To make this a bit more seamless, I've opened https://github.com/williamboman/nvim-lsp-installer/pull/42 which will allow you to target ESLint specifically w/o going through neovim internals, like:

```lua
local eslintls = require("nvim-lsp-installer.extras.eslintls")

eslintls.format()
```

or by just calling the new `:EslintFormat` command. However, I think I will modify that PR a bit to leverage the "fix all code action" code path, rather than the "formatting" one. Semantics, but feels more correct.

As for the autofix-on-save part that VSCode does, after doing some research it seems like the `source.fixAll.*` setting is indeed VSCode's attempt to:

- better structure for performing "fix all" actions across multiple servers
- more easily express VSCode triggers when these "fix all" actions should run, for example
  ```yml
  editor.codeActionsOnSave:
    source.fixAll.eslint: true
    source.fixAll.tslint: true
  ```

I believe it should be fairly easy to hook into the same kind of system if that's what you're looking for, through something like the below which would work with all vscode-based LSP servers (assuming `codeActionOnSave = { enable = true, mode = "all" | "problems" }`):

```lua
for _, client in pairs(vim.lsp.buf_get_clients()) do
    local capabilities = client.supports_method("textDocument/codeAction")
    -- could take this one step further and ensure the "source.fixAll.*" code action is supported
    if capabilities then
        client.request_sync(
            "textDocument/codeAction",
            {
                textDocument = { uri = vim.uri_from_fname(vim.api.nvim_buf_get_name(0)) },
                context = { only = { "source.fixAll" } }
            }, 
        )
    end
end

```

**Comment by sassanh** [comment]
Thanks! I applied the patches of both pull requests manually on my installed packages and eslint autofix started working.
Is there a way to enable/disable format for a specific server, currently it is hardcoded: https://github.com/williamboman/nvim-lsp-installer/pull/42/files#diff-deaede591ab4824f81ce2a9d2420b340cc581ca3b169047fe80c62cf6a717302R27

Or generally is it possible to manually change some parameters of a configuration? I guess `get_default_options` has to play a role here but I couldn't find how to pass the modified version of default options to lspconfig, passing it as the parameters of `server:setup(opts)` didn't work, maybe I did something wrong.

I need it to disable formatting for tsserver so that neovim doesn't prompt me to choose a formatter (specially considering tsserver formatting is incorrect for my setup, more on that later.) One solution would be to run only eslint formatting for typescript, etc files but this way I need to run a different command on `ButWritePre` for typescript, etc files than python files for example. What would be easier is to run the same autocmd for all files but disable/enable/configure formatters for each file type.

tsserver has some parameters for its formatting, for example `insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces`, is it possible to configure these options? Is it possible to configure these options per project?

**Comment by williamboman** [comment]
(sorry for wall of text, but these things often end up being a rabbit hole that I don't mind going down :D)

> Thanks! I applied the patches of both pull requests manually on my installed packages and eslint autofix started working.

:+1:

> Is there a way to enable/disable format for a specific server, currently it is hardcoded: https://github.com/williamboman/nvim-lsp-installer/pull/42/files#diff-deaede591ab4824f81ce2a9d2420b340cc581ca3b169047fe80c62cf6a717302R27

How do you mean? Do you mean which servers should actually respond with something when you execute the `textDocument/formatting` LSP request (aka `vim.lsp.buf.formatting*()` functions)? I believe this should entirely depend on how the LSP server is implemented. ESLint happens to have `format.enabled` as a setting, which when `false` will just ignore any incoming `textDocument/formatting` LSP requests. I think either you can:

- Use the versions of `vim.lsp.buf.formatting*()` functions that prompts you which server you want to send the request to (i.e., not use `vim.lsp.buf.formatting_seq_sync()`)
- Write your own Lua function(s) that sends the formatting request only to the servers you want to format the buffer (see for example [this](https://github.com/williamboman/nvim-lsp-installer/blob/main/lua/nvim-lsp-installer/extras/utils.lua) to conditionally send a request)
- Hope that the LSP servers you use have the ability to disable formatting requests through a setting, and make sure you disable this setting when starting the LSP servers. I would not bet on this option.

> Or generally is it possible to manually change some parameters of a configuration? I guess get_default_options has to play a role here but I couldn't find how to pass the modified version of default options to lspconfig, passing it as the parameters of server:setup(opts) didn't work, maybe I did something wrong.

Hm this should work. Whatever you pass to `server:setup(opts)` should be deep merged with the default options (with whatever you provide taking precedence). So something along the lines of

```lua
local installer = require("nvim-lsp-installer")

local ok, server = installer.get_server("eslintls")
if ok then
  server:setup {
    settings = {
      format = { enable = false }
    }
  }
end
```

> I need it to disable formatting for tsserver so that neovim doesn't prompt me to choose a formatter (specially considering tsserver formatting is incorrect for my setup, more on that later.) One solution would be to run only eslint formatting for typescript, etc files but this way I need to run a different command on ButWritePre for typescript, etc files than python files for example. What would be easier is to run the same autocmd for all files but disable/enable/configure formatters for each file type.

Ah. The way this prompt is implemented today by neovim is that it finds all LSP clients attached to the current buffer, and finds those who have reported that they support formatting. In a perfect world - you could control this by simply changing which client capabilities you provide when initializing a LSP client <-> server connection, but there remains quite a lot of work to get LSP servers onboard with this (not to mention how unclear the spec can be at times, it really is open for interpretation how the entire client <-> server capabilities reconciliation should even work).

What you could try doing now, though, is changing the resolved capabilities of the `tsserver` client in the `on_attach` callback, like so:

```tsx
-- put your conditional wherever you prefer (i.e., only override client.resolved_capabilities for tsserver)
server:setup {
  on_attach = function (client, bufnr)
      client.resolved_capabilities.document_formatting = false
      client.resolved_capabilities.document_range_formatting = false
      ...
  end
}
```

I'm pretty sure the above would remove `tsserver` (or whatever client you do this for) as a candidate for formatting!

> tsserver has some parameters for its formatting, for example insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces, is it possible to configure these options? Is it possible to configure these options per project?

So it seems like you have two options for customizing the formatting options<sup>[1](https://github.com/microsoft/TypeScript/blob/1da18c60d68b316c8b504611467dd6bc86df3948/src/services/types.ts#L976-L996)</sup>:
1. Provide it as a parameter to the `textDocument/formatting` LSP request, which through neovim's builtin functions would be done like so:
```lua
vim.lsp.buf.formatting {
  -- note that this would provide this formatting option to all LSP servers, if you use the vim.lsp.buf.formatting() functions
  insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces = true
}
```
2. Create a `tsmft.json`<sup>[2](https://github.com/theia-ide/typescript-language-server/blob/aea14ef2fddb56d13e245b185d496e3de3a440b1/server/src/lsp-server.ts#L594)</sup> with your formatting settings. This should most likely be put in the same directory as your `tsconfig.json`.

--

All in all, much of these things are still very early stage. Be it the functionality that neovim offers out of the box, or just the maturity of the LSP ecosystem as a whole. I think a big reason the LSP experience is more seamless in VSCode is due to the large amount of "proprietary" and custom glue code that LSP servers have built specifically for VSCode. The open protocol itself helps alleviate this, but there's still quite some work to do.

**Comment by williamboman** [comment]
I think I'll look into the formatting part a bit more - I think what's provided right now is very rudimentary, maybe this plugin could fill in the gaps

**Comment by sassanh** [comment]
I appreciate your time sharing all these valuable knowledge. Now I have a better understanding about what's going on behind the scenes between Neovim and language servers, I think by combining the solutions you provided I can get exactly what I want for different situations.
I think we can close this issue when pull requests are merged. Looking forward to seeing your plan for feeling the gaps :-)

**Comment by williamboman** [comment]
Considering the responses we've gotten upstream - I think it'd make sense to simply do nothing in this plugin, and instead rely on simply overriding the resolved client capabilities (like in your code snippet). ESLint autofix could then be executed via the document formatting request - rendering #42 redundant. Or am I missing something?

**Comment by sassanh** [comment]
Yes, I think it will be probably resolved when Neovim's implementation of LSP supports dynamic registration, there is nothing nvim-lsp-installer can help with as far as I understand.
I close this issue and I think we can close the pull request as well.
