### ISSUE TITLE
Yarn as an alternative to npm

### ISSUE THREAD

**Issue by utilyre** [williamboman/nvim-lsp-installer#458]
### Is your feature request related to a problem? Please describe.

Recently, I decided to switch to yarn package manager (since it's much faster than npm) and realized `:LspInstall` is not capable of installing tsserver and a bunch of other servers with yarn.

### Describe the solution you'd like

So, just like curl and wget that are optional to choose from, it would be nicer if this was the case with npm and yarn too!

**Comment by williamboman** [comment]
Hello @utilyre! This was actually requested some time ago but I'm unable to find the conversation again :/. I'm not particularly interested in adding yarn support at this moment due to the following reasons:

- yarn really doesn't have any performance boosts over npm when installing _single_ packages, which is what this plugin mostly does. If there are any, they'd be negligible. I remember benchmarking this and getting very mixed results.
- yarn support would incur added maintenance complexity, a cost I really don't think is worth paying. The fact that the requirements are relaxed in terms of `curl` vs `wget` vs `gh` etc. is that the expectation of these tools is only to do one thing, whereas npm & yarn are entire package managers of themselves.

I'd be happy to be corrected in case I'm missing something, but for the time being yarn support is a non-goal.

**Comment by utilyre** [comment]
Hi again. I totally agree that adding a new feature always is not a good idea, specially if it brings up more complexity. I'll close the issue.
