### ISSUE TITLE
Emmet_ls

### ISSUE THREAD

**Issue by bryant-the-coder** [williamboman/nvim-lsp-installer#551]
### Is your feature request related to a problem? Please describe.

Yes. Please change aca/emmet_ls to this [emmet](https://github.com/pedro757/emmet)

### Describe the solution you'd like

Change it as it supports more filetypes

**Comment by williamboman** [comment]
Hello! By supports more filetypes, what exactly do you mean? Does the server itself have broader support for more syntaxes (languages) or is it just a matter of LSP client configuration (the filetypes the server should attach to)? As for changing it, this plugin follows what's [in lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/emmet_ls.lua), so I avoid doing so unless there's a very strong reason to

**Comment by bryant-the-coder** [comment]
Emmet_ls and ls_emmet has their own benefits. ls_emmet supports vue js whereas emmet_ls doesnt. So both of this plugins has their own advantages and disadvantages. It's up to your decision. I am just giving suggestion =)

**Comment by williamboman** [comment]
Ah I see. Reason I ask is because I don't use emmet at all and so I don't have a clue about their relative benefits. I'd suggest bringing the conversation upstream to lspconfig first and foremost if you're interested , there was some discussion about this here: https://github.com/neovim/nvim-lspconfig/pull/1295.
