### ISSUE TITLE
julialsp seems to have shipped a faulty config

### ISSUE THREAD

**Issue by uncomfyhalomacro** [williamboman/nvim-lsp-installer#733]
### Problem description

N/A I will open a PR this week to fix it. It shouldn't use julia-vscode config because you dont need it. and it may have caused some issues because there is an update with julia-vscode that might not be compatible with nvim-lspconfig

### Neovim version (>= 0.7)

NVIM 0.7

### Operating system/version

Linux

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [ ] Yes

### Affected language servers

julialsp

### Actual behavior

it uses julia-vscode. it does not need it

### Expected behavior

works. 

### Installation log

```Text
N/A
```

### Healthcheck

```Text
N/A
```

### Screenshots

N/A

**Comment by uncomfyhalomacro** [comment]
a config from https://github.com/neovim/nvim-lspconfig/blob/b86a37caf7a4e53e62ba883aef5889b590260de9/lua/lspconfig/server_configurations/julials.lua#L3-L41 should be enough

**Comment by williamboman** [comment]
> I have a Juliaup installation. The julia-vscode extension should be able to handle this, but it is unable to when installed via lsp-installer. It attempts to call the `julia` executable from a different DEPOT path (`~/.local/share/nvim/lsp_servers/julials/lsdepot`), which doesn't have a julia installation. This points to a configuration issue on lsp-installer side, as a plain install works fine.

Thanks for the explanation! Exactly what errors do you get? The way the DEPOT paths are set up are on purpose, and is mimicked from how the VSCode extension does things. It's been a while since I looked into adding Julia support, so I can't recall all of the details. So, here's what I recall:

1. The idea is that the language server should execute in an isolated environment. Its dependencies and any runtime artifacts should be isolated entirely within the server installation itself. This is for example 1) language server is spawned with a custom [`JULIA_DEPOT_PATH`](https://github.com/williamboman/nvim-lsp-installer/blob/1978757facd4e85a6cc03120016f4503a06008c4/lua/nvim-lsp-installer/servers/julials/init.lua#L68) and 2) it uses the [project environment](https://github.com/williamboman/nvim-lsp-installer/blob/1978757facd4e85a6cc03120016f4503a06008c4/lua/nvim-lsp-installer/servers/julials/init.lua#L62) provided by julia-vscode.
2. The [server cmd](https://github.com/williamboman/nvim-lsp-installer/blob/1978757facd4e85a6cc03120016f4503a06008c4/lua/nvim-lsp-installer/servers/julials/init.lua#L66-L57) is configured to run [this Julia script](https://github.com/williamboman/nvim-lsp-installer/blob/1978757facd4e85a6cc03120016f4503a06008c4/lua/nvim-lsp-installer/servers/julials/init.lua#L22-L7). It receives [these arguments](https://github.com/williamboman/nvim-lsp-installer/blob/1978757facd4e85a6cc03120016f4503a06008c4/lua/nvim-lsp-installer/servers/julials/init.lua#L64-L65) (the _current_ depot path as well as a symbolstore location).
3. The Julia script will run in the "isolated" environment, and import the language server and call it's [`runserver()`](https://github.com/williamboman/nvim-lsp-installer/blob/1978757facd4e85a6cc03120016f4503a06008c4/lua/nvim-lsp-installer/servers/julials/init.lua#L15-L21) function. This function takes a "depot path" as an argument - and this will be sourced from the arguments in `cmd`, which will be equal to `vim.env.JULIA_DEPOT_PATH or ""`. **Question:** I wonder if setting the default value to `":"` might fix your issue, according to the [docs here](https://docs.julialang.org/en/v1/manual/environment-variables/#JULIA_DEPOT_PATH).

Could you see if the branch `fix/julia-depot-path` fixes your issue?

**Comment by williamboman** [comment]
I did some more investigation, looking into how the VSCode extension launches the server. I believe it should be very similar now, see #740. Wdyt?

**Comment by DhruvaSambrani** [comment]
Thanks for the quick response.
I am not entirely sure where the issue is since `julia-vscode` should be able to handle the `juliaup` installation without reinstalling in the new DEPOT, since there is explicit code for this. I agree with point 1.

I am not well versed in neovim package management, and I am using NVChad. How should I be testing that PR?

**Comment by williamboman** [comment]
So neovim plugins are generally just git repos cloned in a specific location (usually in a `:h 'packpath'` location). Nvchad seems to use packer and put it as an optional plugin, so the following should do it:

```sh
$ cd **~/.local/share/nvim/site/pack/packer/opt/nvim-lsp-installer
$ git fetch origin refs/pull/740/head
$ git checkout FETCH_HEAD
```

**Comment by williamboman** [comment]
Ok I feel pretty confident with #740 now, spent quite a lot of effort researching how the VSCode extension launches the server and I believe it should behave very similarly now.

**Comment by DhruvaSambrani** [comment]
Hi! I'm sorry but I will only be able to test this tomorrow ~12 h from now. I will get back ASAP

**Comment by uncomfyhalomacro** [comment]
i can test this later with a vanilla config within 1-2hrs

**Comment by uncomfyhalomacro** [comment]
@williamboman It works now :)
![image](https://user-images.githubusercontent.com/66054069/171093327-c9c1541a-2ec1-4afe-8653-40d364a424b8.png)

Reference config:
```lua
-- Packer
local fn = vim.fn
local install_path = fn.stdpath("data") .. "/site/pack/packer/start/packer.nvim"
if fn.empty(fn.glob(install_path)) > 0 then
	packer_bootstrap = fn.system({
		"git",
		"clone",
		"--depth",
		"1",
		"https://github.com/wbthomason/packer.nvim",
		install_path,
	})
	vim.o.runtimepath = vim.fn.stdpath("data") .. "/site/pack/*/start/*," .. vim.o.runtimepath
end

local packer_status, packer = pcall(require, "packer")
if not packer_status then
	return
end
packer.init({
	git = {
		clone_timeout = 600,
	},
})
local plugins = function(use)
	-- To manage itself
	use({ "wbthomason/packer.nvim" })
	use({
		"neovim/nvim-lspconfig",
	})
	use({
		"williamboman/nvim-lsp-installer",
		branch = "fix/julia-depot-path",
		config = function()
			require("nvim-lsp-installer").setup()
			local capabilities = vim.lsp.protocol.make_client_capabilities()
			capabilities.textDocument.completion.completionItem.preselectSupport = true
			capabilities.textDocument.completion.completionItem.tagSupport = { valueSet = { 1 } }
			capabilities.textDocument.completion.completionItem.deprecatedSupport = true
			capabilities.textDocument.completion.completionItem.insertReplaceSupport = true
			capabilities.textDocument.completion.completionItem.labelDetailsSupport = true
			capabilities.textDocument.completion.completionItem.commitCharactersSupport = true
			capabilities.textDocument.completion.completionItem.resolveSupport = {
				properties = { "documentation", "detail", "additionalTextEdits" },
			}
			capabilities.textDocument.completion.completionItem.documentationFormat = { "markdown" }
			capabilities.textDocument.codeAction = {
				dynamicRegistration = true,
				codeActionLiteralSupport = {
					codeActionKind = {
						valueSet = (function()
							local res = vim.tbl_values(vim.lsp.protocol.CodeActionKind)
							table.sort(res)
							return res
						end)(),
					},
				},
			}

			vim.lsp.handlers["textDocument/publishDiagnostics"] =
				vim.lsp.with(
					vim.lsp.diagnostic.on_publish_diagnostics,
					{
						virtual_text = false,
						underline = false,
						signs = true,
						update_in_insert = false,
					}
				)
			require("lspconfig").pyright.setup({})
			require("lspconfig").julials.setup({})
			require("lspconfig").sumneko_lua.setup({})
		end,
	})
	if packer_bootstrap then
		require("packer").sync()
	end
end

local config = {
	display = {
		open_fn = require("packer.util").float,
	},
}

return packer.startup({
	plugins,
	config = config,
})

```
@DhruvaSambrani it should work for you too :) 

waiting for you to close once it got merged @williamboman. I apologize for my lack of assistance here

**Comment by DhruvaSambrani** [comment]
I can confirm too that it works with NVChad too. Thanks a lot for the super quick resolution
