### ISSUE TITLE
[Feature] Install extra tools (like lua-formatter, eslint_d, prettierd)

### ISSUE THREAD

**Issue by lucax88x** [williamboman/nvim-lsp-installer#95]
I know they're not specifically used as LSP servers but more indirectly but servers like efm or diagnostic, but it would be cool, imho, to have the possibility to install also these external tools, like:

- prettierd
- eslint_d
- lua_formatter

etc.

what do you think?

**Comment by williamboman** [comment]
Hey! Yes this is something I'd like to do in the future too. However I am pretty sure I'd not want to put anything formatter-related in this plugin, but instead start a separate plugin for that purpose specifically. Much of the code in terms of installing, uninstalling, and the UI is very much reusable, so it should not take a lot of effort to make it happen. What's kinda holding me back atm is:

1) I don't feel like I have a good idea of the full inventory of different formatters that exist (I pretty much only use Prettier and Stylua, Checkstyle, Ktlint)
1) I don't have that good of an idea of how such a plugin would best fit in with the existing ecosystem of formatting plugins. I use https://github.com/mhartington/formatter.nvim personally, but I know there are a ton of others. Many are also non-Lua, so that complicates things somewhat.

Might look into this soon, since you created an issue there might be a bigger demand than I anticipated :P

**Comment by ChristianChiarulli** [comment]
I would recommend a companion for [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim), it supports a ton of formatters and linters.

lspconfig - nvim-lsp-installer
null-ls - language-tool-installer

**Comment by williamboman** [comment]
> I would recommend a companion for [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim), it supports a ton of formatters and linters.
> 
> lspconfig - nvim-lsp-installer null-ls - language-tool-installer

I've been meaning to learn more about null-ls. Looks interesting, would definitely help by not having to ensure compatibility with all existing plugins out there.

**Comment by abalmos** [comment]
> lspconfig - nvim-lsp-installer null-ls - language-tool-installer

Could keep it one plugin and ensure that `null-ls` is installed when any of the formatters / linters are. `null-ls` essentially allows you to think of those tools as language servers and seems appropriate for this plugin to me.

That said, many of these tools are often installed locally to a project as a dev dependency (e.g., eslint) and it should use that over the system / nvim-lsp-installer version. This is important for predictable CI, etc.

**Comment by nyngwang** [comment]
> [...] to install also these external tools, like:
> 
> * prettierd
> * eslint_d
> * lua_formatter
> 
> **etc.**

I propose these for python developers too:

- `mypy`
- `flake8`
- `autopep8`

**Comment by williamboman** [comment]
Cross-posting this here: https://github.com/Pocco81/dap-buddy.nvim/issues/71#issuecomment-1106527425

**Comment by williamboman** [comment]
Hello all. So as I've been working on this on-and-off for the past months I've ended up with something that is so fundamentally different from nvim-lsp-installer that I felt like it warranted an entirely new plugin, so that's just what I've done.

I just made https://github.com/williamboman/mason.nvim public for alpha testing. Feel free to give it a spin if you'd like, for the time being only a small set of new packages have been added on top the nvim-lsp-installer base (PRs to add new packages are very much welcomed).
